trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'test-pipeline'
    
- task: TerraformTaskV4@4
  inputs:
        provider: 'azurerm'
        command: 'validate'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'plan'
    commandOptions: '-out=tfplan'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: '-auto-approve tfplan'